import { StyleSheet } from 'react-native';
import { colors, fonts, radius, shadow, spacing } from '../theme';

export const onboardingStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.lg,
  },
  content: {
    flex: 1,
    marginTop: 24,
  },
  heroWrap: {
    alignItems: 'center',
    marginVertical: 12,
  },
  hero: {
    alignItems: 'center',
    marginTop: 40,
  },
  heroIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.blush,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  heroIconSmall: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.blush,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontFamily: fonts.serif,
    fontSize: 30,
    color: colors.textPrimary,
    textAlign: 'center',
  },
  titleCompact: {
    fontFamily: fonts.serif,
    fontSize: 26,
    color: colors.textPrimary,
    textAlign: 'center',
  },
  subtitle: {
    fontFamily: fonts.sans,
    fontSize: 14,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: 6,
  },
  helloText: {
    fontFamily: fonts.serif,
    fontSize: 15,
    color: colors.primary,
    marginTop: 4,
  },
  label: {
    fontFamily: fonts.sansBold,
    fontSize: 11,
    letterSpacing: 1.5,
    color: colors.textMuted,
    marginTop: 20,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  input: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: 16,
    paddingVertical: 15,
    fontFamily: fonts.sansMedium,
    fontSize: 18,
    letterSpacing: 0.5,
    color: colors.textPrimary,
  },
  inputCompact: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontFamily: fonts.sansMedium,
    fontSize: 16,
    color: colors.textPrimary,
  },
  cta: {
    backgroundColor: colors.primary,
    paddingVertical: 15,
    borderRadius: radius.pill,
    alignItems: 'center',
    marginTop: 18,
    marginBottom: 30,
    ...shadow.medium,
  },
  ctaText: {
    fontFamily: fonts.sansBold,
    color: '#FFF',
    fontSize: 15,
  },
  ctaLarge: {
    backgroundColor: colors.primary,
    paddingVertical: 15,
    borderRadius: radius.pill,
    alignItems: 'center',
    marginTop: 20,
    ...shadow.medium,
  },
  cardGrid: {
    gap: 12,
    marginTop: spacing.xl,
  },
  card: {
    flex: 1,
    backgroundColor: colors.surfaceElevated,
    paddingVertical: 22,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    ...shadow.soft,
  },
  cardActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  cardFlag: {
    fontSize: 28,
  },
  cardNative: {
    fontFamily: fonts.serif,
    fontSize: 22,
    color: colors.textPrimary,
    marginTop: 6,
  },
  cardLabel: {
    fontFamily: fonts.sansMedium,
    fontSize: 11,
    color: colors.textMuted,
    marginTop: 2,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  form: {
    marginTop: 40,
  },
  hint: {
    fontFamily: fonts.sans,
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 4,
    marginBottom: 18,
  },
  terms: {
    fontFamily: fonts.sans,
    fontSize: 11,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: 16,
    fontStyle: 'italic',
  },
  roleGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  roleCard: {
    flex: 1,
    backgroundColor: '#FFF',
    padding: 16,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow.soft,
  },
  roleCardActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  roleTitle: {
    fontFamily: fonts.serif,
    fontSize: 17,
    color: colors.textPrimary,
    marginTop: 10,
  },
  roleSub: {
    fontFamily: fonts.sans,
    fontSize: 11,
    color: colors.textMuted,
    marginTop: 4,
    lineHeight: 15,
  },
  phoneText: {
    fontFamily: fonts.sansBold,
    fontSize: 16,
    color: colors.primary,
    marginTop: 6,
  },
  codeRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 30,
  },
  codeBox: {
    width: 44,
    height: 54,
    backgroundColor: '#FFF',
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: radius.md,
    textAlign: 'center',
    fontFamily: fonts.serif,
    fontSize: 24,
    color: colors.textPrimary,
  },
  demoBadge: {
    fontFamily: fonts.sansMedium,
    fontSize: 12,
    color: colors.turmeric,
    marginTop: 20,
    backgroundColor: '#FCE3C8',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: radius.pill,
  },
  verifyingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 20,
  },
  verifyingText: {
    fontFamily: fonts.sansMedium,
    color: colors.primary,
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 30,
  },
  linkText: {
    fontFamily: fonts.sansBold,
    color: colors.primary,
    fontSize: 13,
  },
  expiredBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FCE3C8',
    borderRadius: radius.md,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginTop: 12,
  },
  expiredText: {
    fontFamily: fonts.sansMedium,
    fontSize: 12,
    color: colors.turmeric,
    flexShrink: 1,
  },
});
